# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# CRATES/GIT_CRATES/dependent-crate LICENSE list generated by
# app-portage/pycargoebuild against src-tauri/Cargo.lock.
CRATES="
	Inflector@0.11.4
	adler2@2.0.1
	ahash@0.7.8
	ahash@0.8.12
	aho-corasick@1.1.4
	alloc-no-stdlib@2.0.4
	alloc-stdlib@0.2.2
	allocator-api2@0.2.21
	alsa-sys@0.3.1
	alsa@0.9.1
	android_log-sys@0.3.2
	android_logger@0.15.1
	android_system_properties@0.1.5
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	arbitrary@1.4.2
	arboard@3.6.1
	arrayvec@0.7.6
	async-broadcast@0.7.2
	async-channel@2.5.0
	async-compression@0.4.43
	async-executor@1.14.0
	async-io@2.6.0
	async-lock@3.4.2
	async-process@2.5.0
	async-recursion@1.1.1
	async-signal@0.2.13
	async-task@4.7.1
	async-trait@0.1.89
	atk-sys@0.18.2
	atk@0.18.2
	atomic-waker@1.1.2
	auto-launch@0.5.0
	autocfg@1.5.0
	base64@0.21.7
	base64@0.22.1
	base64ct@1.8.3
	bincode@2.0.1
	bincode_derive@2.0.1
	bit-set@0.8.0
	bit-vec@0.8.0
	bitflags@1.3.2
	bitflags@2.11.0
	bitvec@1.0.1
	block-buffer@0.10.4
	block2@0.6.2
	block@0.1.6
	blocking@1.6.2
	borsh-derive@1.6.0
	borsh@1.6.0
	brotli-decompressor@5.0.0
	brotli@8.0.2
	bumpalo@3.20.2
	byte-unit@5.2.0
	bytecheck@0.6.12
	bytecheck_derive@0.6.12
	bytemuck@1.25.0
	byteorder-lite@0.1.0
	byteorder@1.5.0
	bytes@1.11.1
	cairo-rs@0.18.5
	cairo-sys-rs@0.18.2
	camino@1.2.2
	cargo-platform@0.1.9
	cargo_metadata@0.19.2
	cargo_toml@0.22.3
	cast@0.3.0
	cbindgen@0.29.2
	cc@1.2.56
	cesu8@1.1.0
	cfb@0.7.3
	cfg-expr@0.15.8
	cfg-expr@0.20.6
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chrono@0.4.43
	clap@4.5.60
	clap_builder@4.5.60
	clap_derive@4.5.55
	clap_lex@1.1.0
	clipboard-win@5.4.1
	cmake@0.1.57
	cocoa-foundation@0.1.2
	cocoa@0.24.1
	colorchoice@1.0.5
	combine@4.6.7
	compression-codecs@0.4.38
	compression-core@0.4.32
	concurrent-queue@2.5.0
	console@0.16.3
	convert_case@0.4.0
	cookie@0.18.1
	cookie_store@0.22.1
	core-foundation-sys@0.8.7
	core-foundation@0.10.1
	core-foundation@0.9.4
	core-graphics-types@0.1.3
	core-graphics-types@0.2.0
	core-graphics@0.22.3
	core-graphics@0.25.0
	coreaudio-rs@0.13.0
	cpal@0.16.0
	cpufeatures@0.2.17
	crc32fast@1.5.0
	crossbeam-channel@0.5.15
	crossbeam-utils@0.8.21
	crunchy@0.2.4
	crypto-common@0.1.7
	cssparser-macros@0.6.1
	cssparser@0.29.6
	cssparser@0.36.0
	ctor-proc-macro@0.0.7
	ctor@0.8.0
	darling@0.20.11
	darling@0.21.3
	darling_core@0.20.11
	darling_core@0.21.3
	darling_macro@0.20.11
	darling_macro@0.21.3
	dasp_sample@0.11.0
	dbus@0.9.12
	der@0.7.10
	deranged@0.5.7
	derive_arbitrary@1.4.2
	derive_builder@0.20.2
	derive_builder_core@0.20.2
	derive_builder_macro@0.20.2
	derive_more-impl@2.1.1
	derive_more@0.99.20
	derive_more@2.1.1
	digest@0.10.7
	dirs-sys@0.3.7
	dirs-sys@0.5.0
	dirs@4.0.0
	dirs@6.0.0
	dispatch2@0.3.0
	dispatch@0.2.0
	displaydoc@0.2.5
	dlopen2@0.8.2
	dlopen2_derive@0.4.3
	document-features@0.2.12
	dom_query@0.27.0
	downcast-rs@1.2.1
	dpi@0.1.2
	dtoa-short@0.3.5
	dtoa@1.0.11
	dtor-proc-macro@0.0.6
	dtor@0.3.0
	dunce@1.0.5
	dyn-clone@1.0.20
	embed-resource@3.0.6
	embed_plist@1.2.2
	encode_unicode@1.0.0
	encoding_rs@0.8.35
	endi@1.1.1
	enigo@0.6.1
	enum-map-derive@0.17.0
	enum-map@2.7.3
	enumflags2@0.7.12
	enumflags2_derive@0.7.12
	env_filter@0.1.4
	env_logger@0.10.2
	epoll@4.4.0
	equivalent@1.0.2
	erased-serde@0.4.9
	errno@0.3.14
	error-code@3.3.2
	evdev@0.13.2
	event-listener-strategy@0.5.4
	event-listener@5.4.1
	extended@0.1.0
	eyre@0.6.12
	fallible-iterator@0.3.0
	fallible-streaming-iterator@0.1.9
	fastrand@2.3.0
	fax@0.2.6
	fax_derive@0.2.0
	fdeflate@0.3.7
	fern@0.7.1
	ferrous-opencc-compiler@0.1.0
	ferrous-opencc@0.2.3
	field-offset@0.3.6
	filetime@0.2.27
	find-msvc-tools@0.1.9
	fixedbitset@0.5.7
	flate2@1.1.9
	fnv@1.0.7
	foldhash@0.1.5
	foldhash@0.2.0
	foreign-types-macros@0.2.3
	foreign-types-shared@0.1.1
	foreign-types-shared@0.3.1
	foreign-types@0.3.2
	foreign-types@0.5.0
	form_urlencoded@1.2.2
	fst@0.4.7
	funty@2.0.0
	futf@0.1.5
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-lite@2.6.1
	futures-macro@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	futures@0.3.32
	fxhash@0.2.1
	gdk-pixbuf-sys@0.18.0
	gdk-pixbuf@0.18.5
	gdk-sys@0.18.2
	gdk@0.18.2
	gdkwayland-sys@0.18.2
	gdkx11-sys@0.18.2
	gdkx11@0.18.2
	generic-array@0.14.7
	gethostname@1.1.0
	getrandom@0.1.16
	getrandom@0.2.17
	getrandom@0.3.4
	getrandom@0.4.1
	gio-sys@0.18.1
	gio@0.18.4
	glib-macros@0.18.5
	glib-sys@0.18.1
	glib@0.18.5
	glob@0.3.3
	global-hotkey@0.8.0
	gobject-sys@0.18.0
	gtk-layer-shell-sys@0.7.2
	gtk-layer-shell@0.8.2
	gtk-sys@0.18.2
	gtk3-macros@0.18.2
	gtk@0.18.2
	h2@0.4.13
	half@2.7.1
	handy-keys@0.3.4
	hashbrown@0.12.3
	hashbrown@0.14.5
	hashbrown@0.15.5
	hashbrown@0.16.1
	hashlink@0.10.0
	heck@0.4.1
	heck@0.5.0
	hermit-abi@0.5.2
	hex@0.4.3
	hmac-sha256@1.1.14
	hound@3.5.1
	html5ever@0.29.1
	html5ever@0.38.0
	http-body-util@0.1.3
	http-body@1.0.1
	http-range@0.1.5
	http@1.4.0
	httparse@1.10.1
	humantime@2.3.0
	hyper-rustls@0.27.7
	hyper-tls@0.6.0
	hyper-util@0.1.20
	hyper@1.8.1
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.65
	ico@0.5.0
	icu_collections@2.1.1
	icu_locale_core@2.1.1
	icu_normalizer@2.1.1
	icu_normalizer_data@2.1.1
	icu_properties@2.1.2
	icu_properties_data@2.1.2
	icu_provider@2.1.1
	id-arena@2.3.0
	ident_case@1.0.1
	idna@1.1.0
	idna_adapter@1.2.1
	image@0.25.9
	indenter@0.3.4
	indexmap@1.9.3
	indexmap@2.13.0
	indicatif@0.18.4
	infer@0.19.0
	inotify-sys@0.1.5
	inotify@0.10.2
	ipnet@2.11.0
	iri-string@0.7.10
	is-docker@0.2.0
	is-terminal@0.4.17
	is-wsl@0.4.0
	is_terminal_polyfill@1.70.2
	isolang@2.4.0
	itoa@1.0.17
	javascriptcore-rs-sys@1.1.1
	javascriptcore-rs@1.1.2
	jni-sys@0.3.0
	jni@0.21.1
	js-sys@0.3.87
	json-patch@3.0.1
	jsonptr@0.6.3
	keyboard-types@0.7.0
	kuchikiki@0.8.8-speedreader
	lazy_static@1.5.0
	leb128fmt@0.1.0
	libappindicator-sys@0.9.0
	libappindicator@0.9.0
	libc@0.2.182
	libdbus-sys@0.2.7
	libloading@0.7.4
	libm@0.2.16
	libredox@0.1.12
	libsqlite3-sys@0.35.0
	linux-raw-sys@0.11.0
	litemap@0.8.1
	litrs@1.0.0
	lock_api@0.4.14
	log@0.4.29
	lzma-rust2@0.15.7
	mac@0.1.1
	mach2@0.4.3
	macos-accessibility-client@0.0.1
	malloc_buf@0.0.6
	markup5ever@0.14.1
	markup5ever@0.38.0
	match_token@0.1.0
	matches@0.1.10
	matrixmultiply@0.3.10
	memchr@2.8.0
	memmap2@0.9.10
	memoffset@0.9.1
	mime@0.3.17
	minicov@0.3.8
	minisign-verify@0.2.4
	miniz_oxide@0.8.9
	mio@0.8.11
	mio@1.1.1
	moxcms@0.7.11
	muda@0.19.3
	native-tls@0.2.18
	natural@0.5.0
	ndarray@0.17.2
	ndk-context@0.1.1
	ndk-sys@0.6.0+11769913
	ndk@0.9.0
	new_debug_unreachable@1.0.6
	nix@0.29.0
	nix@0.30.1
	nodrop@0.1.14
	nom@8.0.0
	nu-ansi-term@0.50.3
	num-bigint@0.4.6
	num-complex@0.4.6
	num-conv@0.2.0
	num-derive@0.4.2
	num-integer@0.1.46
	num-rational@0.4.2
	num-traits@0.2.19
	num_cpus@1.17.0
	num_enum@0.7.5
	num_enum_derive@0.7.5
	num_threads@0.1.7
	objc2-app-kit@0.3.2
	objc2-audio-toolbox@0.3.2
	objc2-cloud-kit@0.3.2
	objc2-core-audio-types@0.3.2
	objc2-core-audio@0.3.2
	objc2-core-data@0.3.2
	objc2-core-foundation@0.3.2
	objc2-core-graphics@0.3.2
	objc2-core-image@0.3.2
	objc2-core-location@0.3.2
	objc2-core-text@0.3.2
	objc2-core-video@0.3.2
	objc2-encode@4.1.0
	objc2-exception-helper@0.1.1
	objc2-foundation@0.3.2
	objc2-io-surface@0.3.2
	objc2-metal@0.3.2
	objc2-osa-kit@0.3.2
	objc2-quartz-core@0.3.2
	objc2-security@0.3.2
	objc2-service-management@0.3.2
	objc2-ui-kit@0.3.2
	objc2-user-notifications@0.3.2
	objc2-web-kit@0.3.2
	objc2@0.6.4
	objc@0.2.7
	once_cell@1.21.3
	once_cell_polyfill@1.70.2
	oorandom@11.1.5
	open@5.3.3
	openssl-macros@0.1.1
	openssl-probe@0.2.1
	openssl-sys@0.9.111
	openssl@0.10.75
	option-ext@0.2.0
	ordered-stream@0.2.0
	ort-sys@2.0.0-rc.12
	ort@2.0.0-rc.12
	os_info@3.14.0
	os_pipe@1.2.3
	osakit@0.3.1
	pango-sys@0.18.0
	pango@0.18.3
	parking@2.2.1
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	paste@1.0.15
	pastey@0.1.1
	pathdiff@0.2.3
	pem-rfc7468@0.7.0
	percent-encoding@2.3.2
	petgraph@0.8.3
	phf@0.10.1
	phf@0.11.3
	phf@0.13.1
	phf@0.8.0
	phf_codegen@0.11.3
	phf_codegen@0.13.1
	phf_codegen@0.8.0
	phf_generator@0.10.0
	phf_generator@0.11.3
	phf_generator@0.13.1
	phf_generator@0.8.0
	phf_macros@0.10.0
	phf_macros@0.13.1
	phf_shared@0.10.0
	phf_shared@0.11.3
	phf_shared@0.13.1
	phf_shared@0.8.0
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	piper@0.2.4
	pkg-config@0.3.32
	plist@1.8.0
	png@0.17.16
	png@0.18.1
	polling@3.11.0
	portable-atomic-util@0.2.5
	portable-atomic@1.13.1
	potential_utf@0.1.4
	powerfmt@0.2.0
	ppv-lite86@0.2.21
	precomputed-hash@0.1.1
	prettyplease@0.2.37
	primal-check@0.3.4
	proc-macro-crate@1.3.1
	proc-macro-crate@2.0.2
	proc-macro-crate@3.4.0
	proc-macro-error-attr@1.0.4
	proc-macro-error@1.0.4
	proc-macro-hack@0.5.20+deprecated
	proc-macro2@1.0.106
	ptr_meta@0.1.4
	ptr_meta_derive@0.1.4
	pxfm@0.1.27
	quick-error@2.0.1
	quick-xml@0.38.4
	quote@1.0.44
	r-efi@5.3.0
	radium@0.7.0
	rand@0.7.3
	rand@0.8.5
	rand@0.9.4
	rand_chacha@0.2.2
	rand_chacha@0.3.1
	rand_chacha@0.9.0
	rand_core@0.5.1
	rand_core@0.6.4
	rand_core@0.9.5
	rand_hc@0.2.0
	rand_pcg@0.2.1
	raw-window-handle@0.6.2
	rawpointer@0.2.1
	realfft@3.5.0
	redox_syscall@0.5.18
	redox_syscall@0.7.1
	redox_users@0.4.6
	redox_users@0.5.2
	ref-cast-impl@1.0.25
	ref-cast@1.0.25
	regex-automata@0.4.14
	regex-syntax@0.8.9
	regex@1.12.3
	rend@0.4.2
	reqwest@0.12.28
	reqwest@0.13.2
	rfd@0.16.0
	ring@0.17.14
	ringbuffer@0.15.0
	rkyv@0.7.46
	rkyv_derive@0.7.46
	rubato@0.16.2
	rusqlite@0.37.0
	rusqlite_migration@2.3.0
	rust-stemmers@1.2.0
	rust_decimal@1.40.0
	rustc-hash@2.1.3
	rustc_version@0.4.1
	rustfft@6.4.1
	rustix@1.1.3
	rustls-native-certs@0.8.3
	rustls-pki-types@1.14.0
	rustls-platform-verifier-android@0.1.1
	rustls-platform-verifier@0.6.2
	rustls-webpki@0.103.9
	rustls@0.23.36
	rustversion@1.0.22
	ryu@1.0.23
	same-file@1.0.6
	schannel@0.1.28
	schemars@0.8.22
	schemars@0.9.0
	schemars@1.2.1
	schemars_derive@0.8.22
	scopeguard@1.2.0
	seahash@4.1.0
	security-framework-sys@2.17.0
	security-framework@3.7.0
	selectors@0.24.0
	selectors@0.36.1
	semver@1.0.27
	serde-untagged@0.1.9
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_derive_internals@0.29.1
	serde_json@1.0.149
	serde_repr@0.1.20
	serde_spanned@0.6.9
	serde_spanned@1.0.4
	serde_urlencoded@0.7.1
	serde_with@3.16.1
	serde_with_macros@3.16.1
	serialize-to-javascript-impl@0.1.2
	serialize-to-javascript@0.1.2
	servo_arc@0.2.0
	servo_arc@0.4.3
	sha2@0.10.9
	shlex@1.3.0
	signal-hook-registry@1.4.8
	signal-hook@0.3.18
	simd-adler32@0.3.8
	simdutf8@0.1.5
	siphasher@0.3.11
	siphasher@1.0.2
	slab@0.4.12
	smallvec@1.15.1
	socket2@0.6.2
	socks@0.3.4
	softbuffer@0.4.8
	soup3-sys@0.5.0
	soup3@0.5.0
	specta-macros@2.0.0-rc.18
	specta-serde@0.0.9
	specta-typescript@0.0.9
	specta@2.0.0-rc.22
	stable_deref_trait@1.2.1
	strength_reduce@0.2.4
	string_cache@0.8.9
	string_cache@0.9.0
	string_cache_codegen@0.5.4
	string_cache_codegen@0.6.1
	strsim@0.11.1
	strum@0.24.1
	strum_macros@0.24.3
	subtle@2.6.1
	swift-rs@1.0.7
	symphonia-bundle-flac@0.5.5
	symphonia-bundle-mp3@0.5.5
	symphonia-codec-aac@0.5.5
	symphonia-codec-pcm@0.5.5
	symphonia-codec-vorbis@0.5.5
	symphonia-core@0.5.5
	symphonia-format-isomp4@0.5.5
	symphonia-format-ogg@0.5.5
	symphonia-format-riff@0.5.5
	symphonia-metadata@0.5.5
	symphonia-utils-xiph@0.5.5
	symphonia@0.5.5
	syn@1.0.109
	syn@2.0.117
	sync_wrapper@1.0.2
	synstructure@0.13.2
	sys-locale@0.3.2
	system-configuration-sys@0.6.0
	system-configuration@0.7.0
	system-deps@6.2.2
	system-deps@7.0.7
	tap@1.0.1
	tar@0.4.44
	target-lexicon@0.12.16
	target-lexicon@0.13.3
	tauri-build@2.6.3
	tauri-codegen@2.6.3
	tauri-macros@2.6.3
	tauri-plugin-autostart@2.5.1
	tauri-plugin-clipboard-manager@2.3.2
	tauri-plugin-dialog@2.6.0
	tauri-plugin-fs@2.4.5
	tauri-plugin-global-shortcut@2.3.2
	tauri-plugin-log@2.8.0
	tauri-plugin-macos-permissions@2.3.0
	tauri-plugin-opener@2.5.3
	tauri-plugin-os@2.3.2
	tauri-plugin-process@2.3.1
	tauri-plugin-single-instance@2.4.0
	tauri-plugin-store@2.4.2
	tauri-plugin-updater@2.10.1
	tauri-plugin@2.5.3
	tauri-runtime-wry@2.11.4
	tauri-runtime@2.11.3
	tauri-specta-macros@2.0.0-rc.16
	tauri-specta@2.0.0-rc.21
	tauri-utils@2.9.3
	tauri-winres@0.3.5
	tauri@2.11.5
	tempfile@3.25.0
	tendril@0.4.3
	tendril@0.5.1
	termcolor@1.4.1
	thiserror-impl@1.0.69
	thiserror-impl@2.0.18
	thiserror@1.0.69
	thiserror@2.0.18
	tiff@0.10.3
	time-core@0.1.8
	time-macros@0.2.27
	time@0.3.47
	tinystr@0.8.2
	tinyvec@1.10.0
	tinyvec_macros@0.1.1
	tokio-macros@2.6.0
	tokio-native-tls@0.3.1
	tokio-rustls@0.26.4
	tokio-util@0.7.18
	tokio@1.49.0
	toml@0.8.2
	toml@0.9.12+spec-1.1.0
	toml_datetime@0.6.3
	toml_datetime@0.7.5+spec-1.1.0
	toml_edit@0.19.15
	toml_edit@0.20.2
	toml_edit@0.23.10+spec-1.0.0
	toml_parser@1.0.9+spec-1.1.0
	toml_writer@1.0.6+spec-1.1.0
	tower-http@0.6.8
	tower-layer@0.3.3
	tower-service@0.3.3
	tower@0.5.3
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing@0.1.44
	transcribe-cpp-sys@0.2.0
	transcribe-cpp@0.2.0
	transcribe-rs@0.3.8
	transpose@0.2.3
	tray-icon@0.24.1
	tree_magic_mini@3.2.2
	try-lock@0.2.5
	typeid@1.0.3
	typenum@1.19.0
	uds_windows@1.1.0
	unic-char-property@0.9.0
	unic-char-range@0.9.0
	unic-common@0.9.0
	unic-ucd-ident@0.9.0
	unic-ucd-version@0.9.0
	unicode-ident@1.0.24
	unicode-segmentation@1.12.0
	unicode-width@0.2.2
	unicode-xid@0.2.6
	unit-prefix@0.5.2
	untrusted@0.9.0
	unty@0.0.4
	ureq-proto@0.5.3
	ureq@3.2.0
	url@2.5.8
	urlpattern@0.3.0
	utf-8@0.7.6
	utf8-width@0.1.8
	utf8_iter@1.0.4
	utf8parse@0.2.2
	uuid@1.21.0
	value-bag@1.12.0
	vcpkg@0.2.15
	version-compare@0.2.1
	version_check@0.9.5
	virtue@0.0.18
	vswhom-sys@0.1.3
	vswhom@0.1.0
	walkdir@2.5.0
	want@0.3.1
	wasi@0.11.1+wasi-snapshot-preview1
	wasi@0.9.0+wasi-snapshot-preview1
	wasip2@1.0.2+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-futures@0.4.60
	wasm-bindgen-macro-support@0.2.110
	wasm-bindgen-macro@0.2.110
	wasm-bindgen-shared@0.2.110
	wasm-bindgen-test-macro@0.3.60
	wasm-bindgen-test-shared@0.2.110
	wasm-bindgen-test@0.3.60
	wasm-bindgen@0.2.110
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasm-streams@0.4.2
	wasm-streams@0.5.0
	wasmparser@0.244.0
	wayland-backend@0.3.12
	wayland-client@0.31.12
	wayland-protocols-wlr@0.3.10
	wayland-protocols@0.32.10
	wayland-scanner@0.31.8
	wayland-sys@0.31.8
	web-sys@0.3.87
	web-time@1.1.0
	web_atoms@0.2.5
	webkit2gtk-sys@2.0.2
	webkit2gtk@2.0.2
	webpki-root-certs@1.0.6
	webpki-roots@1.0.8
	webview2-com-macros@0.8.1
	webview2-com-sys@0.38.2
	webview2-com@0.38.2
	weezl@0.1.12
	whatlang@0.16.4
	widestring@1.2.1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	window-vibrancy@0.6.0
	windows-collections@0.2.0
	windows-core@0.54.0
	windows-core@0.58.0
	windows-core@0.61.2
	windows-future@0.2.1
	windows-implement@0.58.0
	windows-implement@0.60.2
	windows-interface@0.58.0
	windows-interface@0.59.3
	windows-link@0.1.3
	windows-link@0.2.1
	windows-numerics@0.2.0
	windows-registry@0.6.1
	windows-result@0.1.2
	windows-result@0.2.0
	windows-result@0.3.4
	windows-result@0.4.1
	windows-strings@0.1.0
	windows-strings@0.4.2
	windows-strings@0.5.1
	windows-sys@0.45.0
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.42.2
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows-threading@0.1.0
	windows-version@0.1.7
	windows@0.54.0
	windows@0.58.0
	windows@0.61.3
	windows_aarch64_gnullvm@0.42.2
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.42.2
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.42.2
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.42.2
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.42.2
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.42.2
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.42.2
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@0.5.40
	winnow@0.7.14
	winreg@0.10.1
	winreg@0.55.0
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-component@0.244.0
	wit-parser@0.244.0
	wl-clipboard-rs@0.9.3
	writeable@0.6.2
	wry@0.55.1
	wyz@0.5.1
	x11-dl@2.21.0
	x11@2.21.0
	x11rb-protocol@0.13.2
	x11rb@0.13.2
	xattr@1.6.1
	xkbcommon@0.9.0
	xkeysym@0.2.1
	yoke-derive@0.8.1
	yoke@0.8.1
	zbus@5.13.2
	zbus_macros@5.13.2
	zbus_names@4.3.1
	zerocopy-derive@0.8.39
	zerocopy@0.8.39
	zerofrom-derive@0.1.6
	zerofrom@0.1.6
	zeroize@1.8.2
	zerotrie@0.2.3
	zerovec-derive@0.11.2
	zerovec@0.11.5
	zip@4.6.1
	zmij@1.0.21
	zune-core@0.4.12
	zune-jpeg@0.4.21
	zvariant@5.9.2
	zvariant_derive@5.9.2
	zvariant_utils@3.3.0
"

declare -A GIT_CRATES=(
	[hf-hub]='https://github.com/cjpais/hf-hub;9918f11ab3473135eb7865aa4a5d79d597e6e810;hf-hub-%commit%'
	[rdev]='https://github.com/rustdesk-org/rdev;a90dbe1172f8832f54c97c62e823c5a34af5fdfe;rdev-%commit%'
	[rodio]='https://github.com/cjpais/rodio;fed30292db417cb95305c118c0e1d804fb74cbff;rodio-%commit%'
	[tao-macros]='https://github.com/cjpais/tao;c3bee28c1d446d95f08c95c3b6f8d4bde052b876;tao-%commit%/tao-macros'
	[tao]='https://github.com/cjpais/tao;c3bee28c1d446d95f08c95c3b6f8d4bde052b876;tao-%commit%'
	[tauri-nspanel]='https://github.com/ahkohd/tauri-nspanel;da9c9a8d4eb7f0524a2508988df1a7d9585b4904;tauri-nspanel-%commit%'
	[vad-rs]='https://github.com/cjpais/vad-rs;2a412ed858695b9251f3f5a1a20d95b59fa7c498;vad-rs-%commit%'
)

inherit cargo desktop udev xdg-utils

DESCRIPTION="A free, open source, and extensible speech-to-text application that works completely offline"
HOMEPAGE="https://handy.computer https://github.com/cjpais/Handy"

# Upstream ships no equivalent of a Cargo/crates.io vendoring tool for the
# Bun-managed frontend (React/Vite), so src_compile runs "bun install" and
# "bun run build" with network access allowed via RESTRICT below.
SRC_URI="
	https://github.com/cjpais/Handy/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
S="${WORKDIR}/Handy-${PV}/src-tauri"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD Boost-1.0
	CDLA-Permissive-2.0 ISC MIT MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

RESTRICT="network-sandbox test"

BDEPEND="
	dev-build/cmake
	dev-lang/bun-bin
	media-libs/shaderc
	dev-util/vulkan-headers
	llvm-core/clang
	virtual/pkgconfig
"

RDEPEND="
	dev-libs/glib:2
	dev-libs/libayatana-appindicator
	dev-libs/libevdev
	dev-libs/openssl:0=
	gui-libs/gtk-layer-shell
	media-libs/alsa-lib
	media-libs/gst-plugins-base
	media-libs/gst-plugins-bad
	media-libs/gst-plugins-good
	media-libs/gst-plugins-ugly
	media-libs/gstreamer
	media-libs/vulkan-loader
	net-libs/libsoup:3.0
	net-libs/webkit-gtk:4.1
	sci-libs/onnxruntime-bin
	x11-libs/gtk+:3
	x11-libs/libXtst
	virtual/udev
"
DEPEND="${RDEPEND}"

QA_FLAGS_IGNORED="usr/bin/handy usr/lib/Handy/.*\.so.*"

src_prepare() {
	default

	# hf-hub and tauri-nspanel are plain git dependencies pinned via
	# branch= in Cargo.toml, so Cargo.lock records their source with a
	# query string (e.g. "git+https://.../hf-hub?branch=...#<sha>") that
	# doesn't match the bare-URL [patch] entries cargo.eclass generates
	# from GIT_CRATES. Strip branch= from both files so they agree on a
	# bare URL (cargo does NOT auto-rewrite a mismatched Cargo.lock git
	# source just because Cargo.toml changed, confirmed by testing --
	# both need editing). The exact commit stays pinned via Cargo.lock's
	# "#<sha>" fragment either way.
	sed -i \
		-e 's/, branch = "cancellable-downloads"//' \
		-e 's/, branch = "v2.1"//' \
		Cargo.toml || die
	sed -i \
		-e 's|hf-hub?branch=cancellable-downloads|hf-hub|' \
		-e 's|tauri-nspanel?branch=v2.1|tauri-nspanel|' \
		Cargo.lock || die

	# tao/tao-macros aren't a plain dependency -- Handy's own Cargo.toml
	# redirects them from crates.io to git via [patch.crates-io]. A
	# config-level [patch] (what GIT_CRATES normally generates) can't
	# override a manifest-level [patch.crates-io] redirect: cargo still
	# tries to fetch the git source live and fails under --offline
	# (confirmed by testing). Point [patch.crates-io] straight at the
	# vendored directory instead, bypassing git entirely for these two.
	sed -i \
		-e "s|tao = { git = \"https://github.com/cjpais/tao\", rev = \"c3bee28c1d446d95f08c95c3b6f8d4bde052b876\" }|tao = { path = \"${WORKDIR}/tao-c3bee28c1d446d95f08c95c3b6f8d4bde052b876\" }|" \
		-e "s|tao-macros = { git = \"https://github.com/cjpais/tao\", rev = \"c3bee28c1d446d95f08c95c3b6f8d4bde052b876\" }|tao-macros = { path = \"${WORKDIR}/tao-c3bee28c1d446d95f08c95c3b6f8d4bde052b876/tao-macros\" }|" \
		Cargo.toml || die
	sed -i \
		-e 's|tao?rev=c3bee28c1d446d95f08c95c3b6f8d4bde052b876|tao|' \
		Cargo.lock || die

	# ferrous-opencc's build.rs shells out to cbindgen to generate a C
	# header (opencc.h) that nothing in this build consumes -- cbindgen
	# in turn runs "cargo metadata" on ferrous-opencc's own Cargo.toml,
	# which fails against our vendored-only registry (a floating
	# "anyhow = ^1" requirement resolves against a stray lockfile
	# instead of the 1.0.102 we actually vendored). Upstream's own Nix
	# packaging (flake.nix postPatch) hits the same failure and disables
	# the cbindgen call the same way; it was removed entirely in
	# ferrous-opencc 0.3.1+.
	sed -i \
		-e 's/\.expect("Unable to generate bindings")/.ok();/' \
		-e 's/\.write_to_file("opencc\.h");/\/\/ skipped: cbindgen disabled, see comment above/' \
		"${ECARGO_HOME}/gentoo/ferrous-opencc-0.2.3/build.rs" || die
}

src_compile() {
	pushd "${WORKDIR}/Handy-${PV}" >/dev/null || die
	bun install --frozen-lockfile || die
	bun run build || die
	popd >/dev/null || die

	ORT_LIB_LOCATION="/usr/lib64" \
	ORT_PREFER_DYNAMIC_LINK=1 \
	OPENSSL_NO_VENDOR=1 \
		cargo_src_compile
}

src_install() {
	dobin target/release/handy

	# The binary's RUNPATH ($ORIGIN/../lib/Handy) and tauri's resource_dir()
	# both resolve to /usr/lib/Handy (matching productName in tauri.conf.json),
	# so the whisper.cpp backend libraries and bundled resources live there.
	insinto /usr/lib/Handy
	doins transcribe-libs/*.so*

	insinto /usr/lib/Handy/resources
	doins -r resources/*

	newicon -s 32 icons/32x32.png handy.png
	newicon -s 64 icons/64x64.png handy.png
	newicon -s 128 icons/128x128.png handy.png

	make_desktop_entry handy Handy handy "Utility;AudioVideo;"

	udev_dorules "${FILESDIR}"/99-handy-uinput.rules
}

pkg_postinst() {
	xdg_icon_cache_update
	udev_reload

	elog "Handy captures global hotkeys and injects text via /dev/uinput,"
	elog "which requires membership in the 'input' group. Add your user with:"
	elog "    usermod -aG input <user>"
	elog "and log out/in for it to take effect."
}

pkg_postrm() {
	xdg_icon_cache_update
	udev_reload
}
